// Code generated by Slice Machine. DO NOT EDIT.

import Bento from './Bento/index.svelte';
import Hero from './Hero/index.svelte';
import Settings from './Settings/index.svelte';

export const components = {
	bento: Bento,
	hero: Hero,
	settings: Settings
};
